### ISSUE TITLE
Not depend on qtpy

### ISSUE THREAD

**Issue by Czaki** [Czaki/sphinx-qt-documentation#1]
@renefritze I see that you try check work with different wrapper of Qt. 

I do not think about this when creating package. 

What you think. It is better to add next wrappers (`qtpy`, `Qt.py`, etc) or add direct import from PyQt5 and PySide2?

**Comment by renefritze** [comment]
Yeah, I'm since we're already using `Qt.py` in our project, I've tried to use that. TBH I'm not quite sure what's best in this situation. Directly importing from different wrappers is tempting, but I'd say that using the wrappers is better: 
 1. Those wrappers let you set preference of one implementation over another. At least `Qt.py` does. Meaning a user of this library will automatically get the same implementation picked as she does in the rest of her library. 
 2. Extensibility: Using the wrappers scales if you need to import more from `Qt` at some future point.

If you agree, I'd be happy to PR a little cleaner approach to using multiple wrappers.

**Comment by Czaki** [comment]
Ok. I see. I'm open on PR with Qt.py. Maybe finally best approach is to allow select Signal and slot in `conf.py` (as addition to predefined wrappers)
